//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mini_Game.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/AC Milan.png.
        /// </summary>
        public static string AC_Milan {
            get {
                return ResourceManager.GetString("AC_Milan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Arsenal.png.
        /// </summary>
        public static string Arsenal {
            get {
                return ResourceManager.GetString("Arsenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Barcelona.png.
        /// </summary>
        public static string Barcelona {
            get {
                return ResourceManager.GetString("Barcelona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Chelsea.png.
        /// </summary>
        public static string Chelsea {
            get {
                return ResourceManager.GetString("Chelsea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Everton.png.
        /// </summary>
        public static string Everton {
            get {
                return ResourceManager.GetString("Everton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Liverpool.png.
        /// </summary>
        public static string Liverpool {
            get {
                return ResourceManager.GetString("Liverpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Manchester City.png.
        /// </summary>
        public static string Manchester_City {
            get {
                return ResourceManager.GetString("Manchester_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Manchester United.png.
        /// </summary>
        public static string Manchester_United {
            get {
                return ResourceManager.GetString("Manchester_United", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu lạc bộ nào giữ kỷ lục vô địch quốc gia (nước Anh) (từ 1889-2018)?.
        /// </summary>
        public static string quiz1 {
            get {
                return ResourceManager.GetString("quiz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reds (Lữ đoàn đỏ) là biệt danh của câu lạc bộ nào?.
        /// </summary>
        public static string quiz10 {
            get {
                return ResourceManager.GetString("quiz10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Quỷ Đỏ&quot; là biệt danh của câu lạc bộ nào?.
        /// </summary>
        public static string quiz2 {
            get {
                return ResourceManager.GetString("quiz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Great Game (1930), một trong những bộ phim sớm nhất về bóng đá, lấy bối cảnh hoạt động của câu lạc bộ nào?.
        /// </summary>
        public static string quiz3 {
            get {
                return ResourceManager.GetString("quiz3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Toffees là biệt danh của câu lạc bộ nào?.
        /// </summary>
        public static string quiz4 {
            get {
                return ResourceManager.GetString("quiz4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu lạc bộ bóng đá của Tây Ban Nha?.
        /// </summary>
        public static string quiz5 {
            get {
                return ResourceManager.GetString("quiz5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll Never Walk Alone trở thành bài hát truyền thống của câu lạc bộ nào?.
        /// </summary>
        public static string quiz6 {
            get {
                return ResourceManager.GetString("quiz6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kình địch của Real Madrid trong những trận El Clásico (Siêu kinh điển)?.
        /// </summary>
        public static string quiz7 {
            get {
                return ResourceManager.GetString("quiz7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu lạc bộ gắn liền với huấn luyện viên Sir Alex Ferguson?.
        /// </summary>
        public static string quiz8 {
            get {
                return ResourceManager.GetString("quiz8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Gunners (Pháo thủ) là biệt danh của câu lạc bộ nào?.
        /// </summary>
        public static string quiz9 {
            get {
                return ResourceManager.GetString("quiz9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Real Madrid.png.
        /// </summary>
        public static string Real_Madrid {
            get {
                return ResourceManager.GetString("Real_Madrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Southampton.png.
        /// </summary>
        public static string Southampton {
            get {
                return ResourceManager.GetString("Southampton", resourceCulture);
            }
        }
    }
}
